version: "2.3"
services:
  web:
    image: mysql
    container_name: myschema
    ports:
      - 9092:9092
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql
    container_name: myschema
    command: mysqld --user=admin
    volumes:
      - ./mysql_dbscript.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=myschema
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=myproject#123
      - MYSQL_ROOT_PASSWORD=myproject#123
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
