cd// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/bxcodec/go-clean-arch/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *Repository) FindAll() ([]models.Role, error) {
	ret := _m.Called()

	var r0 []models.Role
	if rf, ok := ret.Get(0).(func() []models.Role); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRoleName provides a mock function with given fields: roleName
func (_m *Repository) FindByRoleName(roleName string) (models.Role, error) {
	ret := _m.Called(roleName)

	var r0 models.Role
	if rf, ok := ret.Get(0).(func(string) models.Role); ok {
		r0 = rf(roleName)
	} else {
		r0 = ret.Get(0).(models.Role)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
